/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Explorer: typeof import('./src/components/Explorer.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    Play: typeof import('./src/components/Play.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Star: typeof import('./src/components/Star.vue')['default']
  }
}
