INSERT INTO site_info (id, key, name, api, analysis_url, group_name, active, reverse_order)
VALUES (1, '39kan', '39影视', 'https://www.39kan.com/api.php/provide/vod/at/xml', '', '影视', '1', '0'),
       (9, 'apibdzy', '百度云资源', 'https://api.apibdzy.com/api.php/provide/vod/at/xml', '', '影视', '1', '0'),
       (11, 'wolongzyw', '卧龙资源站综合资源', 'https://collect.wolongzyw.com/api.php/provide/vod/at/xml', '', '影视',
        '1', '0'),
       (14, 'xinlangapi', '新浪资源', 'https://api.xinlangapi.com/xinlangapi.php/provide/vod/at/xml', '', '影视', '1',
        '0'),
       (15, 'lziapi', '量子资源', 'https://cj.lziapi.com/api.php/provide/vod/from/liangzi/at/xml', '', '影视', '1',
        '0'),
       (17, 'sdzyapi', '闪电资源网', 'https://sdzyapi.com/api.php/provide/vod/at/xml', '', '影视', '1', '0'),
       (18, 'yparse', '步步高资源', 'https://api.yparse.com/api/xml', '', '影视', '1', '0'),
       (19, 'ckzy', 'CK资源', 'https://ckzy.me/api.php/provide/vod/at/xml', '', '影视', '1', '0'),
       (21, 'guangsuapi', '光速资源', 'https://api.guangsuapi.com/api.php/provide/vod/at/xml', '', '影视', '1', '0'),
       (23, 'tiankongapi', '天空资源', 'https://api.tiankongapi.com/api.php/provide/vod/at/xml/from/tkm3u8', '', '影视',
        '1', '0'),
       (24, 'bajiecaiji', '八戒采集', 'http://cj.bajiecaiji.com/inc/bjm3u8.php', '', '影视', '1', '0'),
       (27, 'zzrhgg', '飘花资源', 'http://www.zzrhgg.com/api.php/provide/vod/at/xml', '', '影视', '1', '0'),
       (32, 'apilyzy', '老鸭', 'https://api.apilyzy.com/api.php/provide/vod/at/xml', '', '18+', '1', '0'),
       (37, 'wmcj8', 'AG资源', 'http://wmcj8.com/inc/sapi.php', '', '18+', '1', '0'),
       (41, 'lb', '乐播', 'https://lbapi9.com/api.php/provide/vod/at/xml', '', '18+', '1', '0'),
       (42, 'bttcj', 'BT天堂', 'http://bttcj.com/inc/sapi.php', '', '18+', '1', '0'),
       (59, 'tky', '天空云', 'https://api.tiankongapi.com/api.php/provide/vod/at/xml/from/tkm3u8/', '', '常用组', '1',
        '0'),
       (60, 'bjcj', '八戒云', 'http://cj.bajiecaiji.com/inc/bjm3u8.php', '', '常用组', '1', '0');